
export const GET_SUBMENU_REQUEST = 'GET_SUBMENU_REQUEST';
export const GET_SUBMENU_SUCCESS = 'GET_SUBMENU_SUCCESS';
export const GET_SUBMENU_FAILURE = 'GET_SUBMENU_FAILURE';

export const ADD_SUBMENU_REQUEST = 'ADD_SUBMENU_REQUEST';
export const ADD_SUBMENU_SUCCESS = 'ADD_SUBMENU_SUCCESS';
export const ADD_SUBMENU_FAILURE = 'ADD_SUBMENU_FAILURE';

export const EDIT_SUBMENU_REQUEST = 'EDIT_SUBMENU_REQUEST';
export const EDIT_SUBMENU_SUCCESS = 'EDIT_SUBMENU_SUCCESS';
export const EDIT_SUBMENU_FAILURE = 'EDIT_SUBMENU_FAILURE';

export const DELETE_SUBMENU_REQUEST = 'DELETE_SUBMENU_REQUEST';
export const DELETE_SUBMENU_SUCCESS = 'DELETE_SUBMENU_SUCCESS';
export const DELETE_SUBMENU_FAILURE = 'DELETE_SUBMENU_FAILURE';