
export const GET_NOTIFICATIONS_REQUEST = 'GET_NOTIFICATIONS_REQUEST';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAILURE = 'GET_NOTIFICATIONS_FAILURE';

export const ADD_NOTIFICATIONS_REQUEST = 'ADD_NOTIFICATIONS_REQUEST';
export const ADD_NOTIFICATIONS_SUCCESS = 'ADD_NOTIFICATIONS_SUCCESS';
export const ADD_NOTIFICATIONS_FAILURE = 'ADD_NOTIFICATIONS_FAILURE';

export const EDIT_NOTIFICATIONS_REQUEST = 'EDIT_NOTIFICATIONS_REQUEST';
export const EDIT_NOTIFICATIONS_SUCCESS = 'EDIT_NOTIFICATIONS_SUCCESS';
export const EDIT_NOTIFICATIONS_FAILURE = 'EDIT_NOTIFICATIONS_FAILURE';

export const DELETE_NOTIFICATIONS_REQUEST = 'DELETE_NOTIFICATIONS_REQUEST';
export const DELETE_NOTIFICATIONS_SUCCESS = 'DELETE_NOTIFICATIONS_SUCCESS';
export const DELETE_NOTIFICATIONS_FAILURE = 'DELETE_NOTIFICATIONS_FAILURE';