
export const GET_ROLE_PRIVILEGE_REQUEST = 'GET_ROLE_PRIVILEGE_REQUEST';
export const GET_ROLE_PRIVILEGE_SUCCESS = 'GET_ROLE_PRIVILEGE_SUCCESS';
export const GET_ROLE_PRIVILEGE_FAILURE = 'GET_ROLE_PRIVILEGE_FAILURE';

export const ADD_ROLE_PRIVILEGE_REQUEST = 'ADD_ROLE_PRIVILEGE_REQUEST';
export const ADD_ROLE_PRIVILEGE_SUCCESS = 'ADD_ROLE_PRIVILEGE_SUCCESS';
export const ADD_ROLE_PRIVILEGE_FAILURE = 'ADD_ROLE_PRIVILEGE_FAILURE';

export const EDIT_ROLE_PRIVILEGE_REQUEST = 'EDIT_ROLE_PRIVILEGE_REQUEST';
export const EDIT_ROLE_PRIVILEGE_SUCCESS = 'EDIT_ROLE_PRIVILEGE_SUCCESS';
export const EDIT_ROLE_PRIVILEGE_FAILURE = 'EDIT_ROLE_PRIVILEGE_FAILURE';

export const DELETE_ROLE_PRIVILEGE_REQUEST = 'DELETE_ROLE_PRIVILEGE_REQUEST';
export const DELETE_ROLE_PRIVILEGE_SUCCESS = 'DELETE_ROLE_PRIVILEGE_SUCCESS';
export const DELETE_ROLE_PRIVILEGE_FAILURE = 'DELETE_ROLE_PRIVILEGE_FAILURE';