
export const GET_USER_ROLE_REQUEST = 'GET_USER_ROLE_REQUEST';
export const GET_USER_ROLE_SUCCESS = 'GET_USER_ROLE_SUCCESS';
export const GET_USER_ROLE_FAILURE = 'GET_USER_ROLE_FAILURE';

export const ADD_USER_ROLE_REQUEST = 'ADD_USER_ROLE_REQUEST';
export const ADD_USER_ROLE_SUCCESS = 'ADD_USER_ROLE_SUCCESS';
export const ADD_USER_ROLE_FAILURE = 'ADD_USER_ROLE_FAILURE';

export const EDIT_USER_ROLE_REQUEST = 'EDIT_USER_ROLE_REQUEST';
export const EDIT_USER_ROLE_SUCCESS = 'EDIT_USER_ROLE_SUCCESS';
export const EDIT_USER_ROLE_FAILURE = 'EDIT_USER_ROLE_FAILURE';

export const DELETE_USER_ROLE_REQUEST = 'DELETE_USER_ROLE_REQUEST';
export const DELETE_USER_ROLE_SUCCESS = 'DELETE_USER_ROLE_SUCCESS';
export const DELETE_USER_ROLE_FAILURE = 'DELETE_USER_ROLE_FAILURE';